name = "MPEC"
authors = ["Pierre Walker <pjwalker@caltech.edu>"]
version = "0.1.0"

[deps]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Clapeyron = "0.4,0.5"
GenericLinearAlgebra = "0.3"
ForwardDiff = "^0.10"
LinearAlgebra = "1"
julia = "1.6"
